### PR TITLE
Better reflect unprotected site status

### PR DESCRIPTION
**Pull request by SlayterDev**
Task/Issue URL: https://app.asana.com/0/0/1200522354297651/f
Tech Design URL:
CC: @brindy @tomasstrba 

**Description**:
This PR better reflects when a site is unprotected due to breakage.

**Steps to test this PR**:
1. Visit https://spiegel.de
1. Privacy dashboard should show protections disabled and a disclaimer explaining the breakage status.

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by tomasstrba** [comment]
@SlayterDev, the dashboard shows the disclaimer, unfortunately the layout is a bit broken.

1. There are no bottom buttons
2. The ‘Encrypted connection’ row has a different height than the ’N trackers found’ row

original
new

**Comment by SlayterDev** [comment]
> @SlayterDev, the dashboard shows the disclaimer, unfortunately the layout is a bit broken.
> 
>     1. There are no bottom buttons
> 
>     2. The ‘Encrypted connection’ row has a different height than the ’N trackers found’ row
>

1. This is intended per the design.

2. The storyboard was giving me trouble here. I was having issues getting the heights to be consistent without messing up the entire UI.

**Comment by tomasstrba** [comment]
@SlayterDev, I’ve tried a different approach and placed the disclaimer on top of headers, as it is designed here - https://app.asana.com/0/1142021229838617/1200538375697100/f

Could you review please?

**Comment by SlayterDev** [comment]
Looks good to me!

**Review by tomasstrba — APPROVED** [review]

**Pull request merged**
